Wphu/add sex check
broadinstitute/tgg_methods pull request #44
Opened 2022-05-06 17:51 UTC by williamphu

More merges:

First one from `get_ibd` is more simple - moving the logger so that remap_hts has values, and updating arguments being passed

and the second is the `sex_check` file that was originally a notebook.

2022-05-06 21:09 UTC, ch-kr requested changes
thanks for adding the sex check code! I have some suggestions but wasn't sure how much to add, as I'm hoping the summer students can productionize this code.

Other small comments/questions:

- The imports in the IBD script should likely be reordered
- The IBD script includes the `no_whole_stage_codegen` flag -- is this still required?
- The code has some formatting issues (easily fixed with BLACK)

2022-05-06 21:09 UTC, ch-kr commented on tgg/seqr_scripts/sex_check.py
> +    # filter to biallelics might be a function
```suggestion
    # Filter to SNVs and biallelics
```

2022-05-06 21:09 UTC, ch-kr commented on tgg/seqr_scripts/sex_check.py
> +    # filter to biallelics might be a function
I found from `gnomad.utils.annotations import bi_allelic_expr`, but this is fine

2022-05-06 21:09 UTC, ch-kr commented on tgg/seqr_scripts/sex_check.py
> +    # gnomad methods - will need to make this an optional argument
```suggestion
    # Filter to pass variants only (empty set)
    # TODO: Make this an optional argument before moving to gnomad_methods
```

2022-05-06 21:09 UTC, ch-kr commented on tgg/seqr_scripts/sex_check.py
> +    #infer build:
```suggestion
    # Infer build:
```

2022-05-06 21:09 UTC, ch-kr commented on tgg/seqr_scripts/sex_check.py
> +    logging.info("Build inferred as {build}".format(**locals()))
```suggestion
    logging.info("Build inferred as %s", build)
```

2022-05-06 21:09 UTC, ch-kr commented on tgg/seqr_scripts/sex_check.py
> +    #for production change female and male to XX and XY
```suggestion
    # TODO: Change female and male to XX and XY
```

2022-05-06 21:09 UTC, ch-kr commented on tgg/seqr_scripts/sex_check.py
> +    outfile = outdir + f"/sex_{mt_name}.txt"
```suggestion
    outfile = f"{outdir}/sex_{mt_name}.txt"
```

2022-05-06 21:09 UTC, ch-kr commented on tgg/seqr_scripts/sex_check.py
> +    parser.add_argument('-c', '--call-rate-threshold', help='call_rate_threshold required to use chrY variant', default=0.25)
```suggestion
    parser = argparse.ArgumentParser(description='This script infers the sex of samples')
    parser.add_argument('-i', '--callset', required=True, help='Path to Callset MatrixTable')
    parser.add_argument('-u', '--use-y-cov', help='Boolean for whether or not to use chrY coverage', action='store_true')
    parser.add_argument('-y', '--y-cov-threshold', help='chrY coverage threshold', default=0.1)
    parser.add_argument('-m', '--male-fstat-threshold', help='Male f-stat threshold for `hl.impute_sex`', default=0.75)
    parser.add_argument('-f', '--female-fstat-threshold', help='Female f-stat threshold for `hl.impute_sex`', default=0.50)
    parser.add_argument('-a', '--aaf-threshold', help='Alternate allele frequency threshold for `hl.impute_sex`', default=0.05)
    parser.add_argument('-c', '--call-rate-threshold', help='Call rate threshold used to filter chrY variants', default=0.25)
```

2022-05-06 21:09 UTC, ch-kr commented on tgg/seqr_scripts/sex_check.py
> +    main(args)
might also be helpful to add slack configuration (also could be a TODO)

2022-06-06 17:28 UTC, klaricch commented on tgg/seqr_scripts/sex_check.py
> +    # filter to common snvs above defined callrate (because only biallelic, should now only have one index in the array)
here and throughout snvs -> SNVs

2022-07-29 15:46 UTC, merged